### ISSUE TITLE
IMPROVEMENT: broadcast my device name after I accepted invitation

### ISSUE THREAD

**Issue by DanielLaanpere** [BindCreative/obbychat#26]
When I accept some one else's invitation, I must send pairing info back with my device name

**Comment by tarmo888** [comment]
Sometimes, it doesn't work properly.

**Comment by tarmo888** [comment]
Probably related to this bug https://github.com/BindCreative/obbychat/issues/23

**Comment by tarmo888** [comment]
Seems to be fixed, can be improved with push notifications https://github.com/BindCreative/obbychat/issues/41
