### ISSUE TITLE
Chat view action - send bytes to contact

### ISSUE THREAD

**Issue by alvarlaigna** [BindCreative/obbychat#7]

**Comment by tarmo888** [comment]
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L195
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L397

https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L197
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L399

https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L781
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L795
