### ISSUE TITLE
Chat view action - ask bytes from contact

### ISSUE THREAD

**Issue by alvarlaigna** [BindCreative/obbychat#8]

**Comment by tarmo888** [comment]
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L177
https://github.com/byteball/obyte-gui-wallet/blob/240319a15e0a09f154d05122b2e3ac85c43579ce/src/js/services/correspondentListService.js#L371
